# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10)),
                ('titolo', models.CharField(max_length=50)),
                ('autore', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
                ('valutazione', models.CharField(max_length=10)),
                ('prezzo', models.CharField(max_length=10)),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
